### ISSUE TITLE
Use shared env variables in `!PR.yml`

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7138]
We can replace hardcoded variables like `pyhon-version` by shared env.

See an example:

```yml
name: PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  env:
    name: Setup Shared Environment Variables
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.setter.outputs.python-version }}
    env:
      PYTHON_VERSION: 3.8
    steps:
      - id: setter
        run: |
          echo "python-version=${PYTHON_VERSION}" >> $GITHUB_OUTPUT

  test:
    needs: [ env ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{needs.env.outputs.python-version}}
```

Ref:
* https://github.com/orgs/community/discussions/26671
* https://github.com/cardinalby/export-env-action
