### ISSUE TITLE
Add Docker build Action

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#8105]
It should be relatively easy to build Docker images using GitHub Actions, taken from https://docs.docker.com/build/ci/github-actions/share-image-jobs/ :

```yml
name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: myimage:latest
          outputs: type=docker,dest=/tmp/myimage.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myimage
          path: /tmp/myimage.tar
```

If we automatically publish images, we also do not have to worry about maintaining (as much) documentation.
